### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Amsterdamys** [horprogs/vue-ssr-hmr#1]
1) Run yarn run dev (
![yarn-run](https://user-images.githubusercontent.com/3232259/65883052-ec482600-e39e-11e9-80f1-fb721900711a.png)
)
2) Open http://localhost:9999/

See: ![result](https://user-images.githubusercontent.com/3232259/65883028-e4888180-e39e-11e9-8361-86aff4d00caf.png)

**Comment by horprogs** [comment]
Application will be available on http://localhost:3000/. Port 9999 for webpack-dev-server

**Comment by Amsterdamys** [comment]
No it's not. Am I right that that's the line where the port sets? https://github.com/horprogs/vue-ssr-hmr/blob/master/app/server.js#L43

I tried to change it. Does not work anyway.

![3000-port](https://user-images.githubusercontent.com/3232259/65885600-9cb82900-e3a3-11e9-9010-15341a0f91bd.png)

**Comment by Amsterdamys** [comment]
As I see the server just does not run wen I execute _yarn run dev_.

So in addition a opened the second tab and executed _node app/server.js_. Now it works correctly and the port responds.

But strange why server does not start with _run dev_ command.

**Comment by Amsterdamys** [comment]
By changing the dev command to that I made it work correctly

...
_"dev": "run-p dev-client dev-server **start-node**",_
...

**Comment by horprogs** [comment]
start-node only starts node process, but dev-server starts nodemon, which watches for files changing and restarts node process. You don't need to run both these commands. 

Yes, I see that dev-server doesn't start. Do you use Windows? Maybe because of this. I didn't test it on Windows

**Comment by Amsterdamys** [comment]
Yes, I use Windows

**Comment by horprogs** [comment]
You can try to change it on `"dev": "yarn run dev-client & yarn run dev-server",`

**Comment by Amsterdamys** [comment]
No this is also not working ("This site can’t be reached")

**Comment by horprogs** [comment]
Okey, today I'll check it on Windows. It's very strange. 
So, while you can run `yarn run dev-client` and `yarn run dev-server` in two terminals :)

**Comment by horprogs** [comment]
I pushed update. Please, check

**Comment by Amsterdamys** [comment]
Works excellent now. Many thanks :)

**Comment by horprogs** [comment]
You're welcome)
