### ISSUE TITLE
Meta description not showing in Google

### ISSUE THREAD

**Issue by jacquesmatthieu** [horprogs/vue-ssr-hmr#12]
Hello,
I've used your boiterplate into my project. 

When I make search with Google my meta description not appear.
<img width="710" alt="Capture d’écran 2020-01-15 à 09 12 49" src="https://user-images.githubusercontent.com/3845269/72416595-57174480-3777-11ea-8366-4cfb917c3e5e.png">

But when I inspect the DOM I can see the meta description, do you know what's the problem ?

```
<meta data-vue-meta="ssr" data-vmid="description" name="description" content="Calculez rapidement et facilement votre moyenne au bac général 2021 ! Saisissez les notes que vous connaissez déjà (bulletins scolaires, épreuves communes...). Le simulateur s’occupe du reste !">
 
```
My app is here => https://www.letudiant.fr/bac/simulateur-de-moyenne-au-bac/bac-general.html

**Comment by horprogs** [comment]
Hello! Thank you for using this boilerplate. Matter is that Google has to index your page and it has own system for deciding how your search snippet should be shown.
Your meta tags looks correct. You can check it by your own, for example using this service https://metatags.io/

**Comment by horprogs** [comment]
BTW, I see your page properly

![image](https://user-images.githubusercontent.com/14051960/72419997-fa278880-378e-11ea-96c8-c77cd2f9c1a6.png)

**Comment by jacquesmatthieu** [comment]
Your screenshot is from Google or metatags ?

**Comment by horprogs** [comment]
From Google

**Comment by jacquesmatthieu** [comment]
Ok thx for all ;)

**Comment by horprogs** [comment]
You're welcome)
