### ISSUE TITLE
This vue app/component has no vue-meta configuration TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by duongnv05** [horprogs/vue-ssr-hmr#13]
When I run project, don't working

This vue app/component has no vue-meta configuration
TypeError: Cannot read property 'text' of undefined

-pls  help me

**Comment by horprogs** [comment]
Hey! It's weird.. I can't reproduce that.  Could you provide more details? Did you run `yarn run dev` command? What version of Nodejs do you use?

**Comment by duongnv05** [comment]
Tks for reply. I fixed. I customized your struture, so this error is incurrent. I fogot metaInfo into Component, so this vue/meta is undefined.

**Comment by horprogs** [comment]
By the way, in my new project I've got the same error. In app.js constructor must have metaInfo

``` 
const app = new Vue({
    router,
    store,
    render: h => h(App),
    metaInfo: {},
  });
```

It works for me
