### ISSUE TITLE
Problem with inject the favicon

### ISSUE THREAD

**Issue by farreldev** [horprogs/vue-ssr-hmr#17]
how to inject a favicon into the head tag? and where do I put the favicon file? please help

**Comment by horprogs** [comment]
Hey! You could add link to favicon to html template and setup express to serve static files. I've added the example: https://github.com/horprogs/vue-ssr-hmr/commit/952a45e5be80c67e52011c7d78fecfbf70d8f0c8

**Comment by farreldev** [comment]
> Hey! You could add link to favicon to html template and setup express to serve static files. I've added the example: [952a45e](https://github.com/horprogs/vue-ssr-hmr/commit/952a45e5be80c67e52011c7d78fecfbf70d8f0c8)

Thank u so much @horprogs
