### ISSUE TITLE
How easy would it be to build Cross-Platform app based on this boilerplate?

### ISSUE THREAD

**Issue by Catsvilles** [horprogs/vue-ssr-hmr#7]
Hi, I'm just planning to get started with Vue for my next project and I really like the boilerplate you've put together as I would love to have exactly these features (SSR, Code-splitting etc) but also I would like to be able easily convert my web app to electron, mobile apps. How easy would it be to achive this with this template and overall with Vue? I know about Quasar but it seems a little bit to much of what I need.

**Comment by horprogs** [comment]
Thank you! Oohh, I guess you can't use this boilerplate for electron and mobile apps (and maybe you don't need it). You could try to discover Vue Native for mobile apps, and Electron-vue (as far as I know it has good ecosystem for development). I think you could share pieces of code between web, electron and mobile apps, but I don't know how to create one boilerplate for all platforms.

https://github.com/GeekyAnts/vue-native-core
https://github.com/SimulatedGREG/electron-vue

Good luck!

**Comment by Catsvilles** [comment]
@horprogs Thank you for your reply! Yeah, I guess in the end it's even better to go with Quasar as there everything comes out of box.
