### ISSUE TITLE
Can i use packages which doesn't have ssr support?

### ISSUE THREAD

**Issue by sathish76** [horprogs/vue-ssr-hmr#8]
I'm using some external npm packages in my project. some of them are not SSR supported. The compilation is successful but I'm getting internal server error.
`ReferenceError: document is not defined`

**Comment by horprogs** [comment]
Hi! On server side you can't use packages which use client-side variables, like `document`, `window` etc. 

But you could try to import this packages only on client-side inside `mounted` hook, using webpack dynamic import (https://webpack.js.org/guides/code-splitting/#dynamic-imports). It will execute only on client-side and you avoid errors on server-side.
